### ISSUE TITLE
False positives for Storybook shots

### ISSUE THREAD

**Issue by e-e-e** [lost-pixel/lost-pixel#377] opened 2024-02-19 01:18 UTC
### Bug description

We are noticing a lot of false positives in our visreg tests for storybook. The height of the story seems to be variable. Sometimes truncating the stories.

Please see attached image:
<img width="1114" alt="image" src="https://github.com/lost-pixel/lost-pixel/assets/12589522/730bb6f6-932a-479e-b255-4eaaea7c1f9e">

### How to reproduce

using simple config like:
```js
module.exports = {
  storybookShots: {
    storybookUrl: './storybook-static',
  },
  lostPixelProjectId: 'your-id',
  apiKey: process.env.LOST_PIXEL_API_KEY,
};
```

And storybook config:
```
const config: StorybookConfig = {
  stories: ['../src/**/*.stories.@(ts|tsx)'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
  ],
  framework: {
    name: '@storybook/nextjs',
    options: {},
  },
  docs: {
    autodocs: 'tag',
  },
  features: {
    storyStoreV7: true,
  },
};
```

1. Build storybook
2. Use lost-pixel v3.4.0 image to upload diffs
3. See false negatives in lost-pixel app.

### Expected behavior

We would expect consistent image size between builds

**Comment by d-ivashchuk** [comment] 2024-02-21 19:23
hey @e-e-e! could you please try the most up to date version of lost pixel first. If you storybook build is not public and you are on the platform we could look at it together in our shared slack or private discord channel, this could move things way faster!

**Comment by d-ivashchuk** [comment] 2024-02-21 19:28
It would be 3.13.0

**Comment by e-e-e** [comment] 2024-02-22 03:51
Thanks @d-ivashchuk I will update our version and see if it addresses the issue

**Comment by mbaumanndev** [comment] 2024-03-15 10:19
I have the same issue with version 3.16.0, my pipelines are failing randomly
![atoms-alert--default](https://github.com/lost-pixel/lost-pixel/assets/499268/1592a116-8ed7-4831-8721-3bfdf79b8ff3)

Here the margins appeared on the right and the bottom

**Comment by d-ivashchuk** [comment] 2024-03-15 10:54
I guess guys bumped up their runners to beefier machines and it started working pretty well for them. So in this regard I don't see a problem in the lost pixel or playwright. Still we can investigate and see what's wrong? Any public repo or reproduction of this I can look at?

**Comment by benevbright** [comment] 2024-03-18 14:15
having the same issue with Storybook 8 + nextjs 14

**Comment by mbaumanndev** [comment] 2024-03-18 15:48
> I guess guys bumped up their runners to beefier machines and it started working pretty well for them. So in this regard I don't see a problem in the lost pixel or playwright. Still we can investigate and see what's wrong? Any public repo or reproduction of this I can look at?

I'll try to make a plublic repo with a repro tomorrow, I can't bump my runners for the moment, I'll just use the ones provided by GH

**Comment by d-ivashchuk** [comment] 2024-03-18 15:50
yeah, if we can somehow remedy this on our side - would be happy to do so! reproduction would be very helpful!

@benevbright @mbaumanndev - you are running in OSS mode, right?

**Comment by mbaumanndev** [comment] 2024-03-18 15:51
Yes, I'm in OSS mode running on GitHub Actions

**Comment by d-ivashchuk** [comment] 2024-03-18 15:52
then please do a repro - would allow us to tackle it properly 🙇🏼‍♂️ thanks a lot!

**Comment by benevbright** [comment] 2024-03-18 16:28
Yes, we're also OSS mode. 

one finding is that when I reduced `shotConcurrency` to 5 from 10, it gives the correct result. `shotConcurrency: 10` was working ok with Storybook 6 + Nextjs 13.0. But after updating these dependencies, the worker seems a bit overwhelmed. 

So from my end, it might not be LostPixel's problem. But what I do want to suggest is how LP starts concurrent jobs. As just my quick guess, it you put a small arbitrary delay between each jobs in one concurrent, it might help to increase this number in our config (just total guess)

**Comment by benevbright** [comment] 2024-03-18 16:30
Sorry, I might have said it too early.... even with `shotConcurrency: 5`, sometimes it gives result with wrong height as this issue described.

**Comment by benevbright** [comment] 2024-03-18 16:55
and it's happening only with heavy pages.

**Comment by d-ivashchuk** [comment] 2024-04-18 09:39
Closing this as it seems like the problem is clear. If anybody needs more assistance - feel free to reopen!

**Closed by d-ivashchuk** 2024-04-18 09:39 UTC
